"""
WebSocket router — mounts the /ws/garden/{room_id} endpoint.

Lifecycle per connection
------------------------
1. ``connect`` — accept and register with :class:`~app.ws.connection_manager.ConnectionManager`.
2. Receive loop — forward every incoming JSON message to the room's Redis
   Pub/Sub channel so that sibling container instances are notified.
3. Disconnect (normal or abnormal) — deregister from the manager.

Why we publish to Redis on receipt
-----------------------------------
A client message must reach *all* connections in the room, including those
held by other container replicas.  Publishing to Redis ensures that every
instance's Pub/Sub listener (``app.pubsub.listener``) picks up the event and
calls :meth:`~app.ws.connection_manager.ConnectionManager.broadcast` locally.
The originating instance also receives its own publish via the listener, which
means the sender sees their own action reflected back — this is intentional and
simplifies the React canvas reconciliation loop.
"""

from __future__ import annotations

import json
import logging

from fastapi import APIRouter, WebSocket, WebSocketDisconnect
from redis.asyncio import Redis

from app.config import settings
from app.pubsub.listener import room_listener_registry
from app.ws.connection_manager import manager

logger = logging.getLogger(__name__)

router = APIRouter()


@router.websocket("/ws/garden/{room_id}")
async def garden_websocket(websocket: WebSocket, room_id: str) -> None:
    """Handle the full lifecycle of a single garden WebSocket connection.

    The endpoint follows a *receive-and-publish* pattern: incoming client
    payloads are validated as JSON and forwarded to the room's Redis Pub/Sub
    channel.  The Redis listener running in the background then fans the
    message out to all local connections (see ``app.pubsub.listener``).

    LWW constraint
    ~~~~~~~~~~~~~~
    Clients **must** include a ``timestamp`` field (Unix milliseconds) in every
    payload.  The server does not enforce this — it is a contract between the
    React canvas and the conflict resolver — but any payload missing
    ``timestamp`` will be broadcast as-is and clients will fall back to
    unconditional apply, risking visual rubber-banding under concurrent edits.

    Args:
        websocket: FastAPI-managed WebSocket connection.
        room_id: Opaque room identifier, typically a UUID generated by the
            React client when creating a new collaborative session.

    Raises:
        WebSocketDisconnect: Raised by Starlette when the client closes the
            connection; caught here to ensure clean deregistration.
    """
    await manager.connect(websocket, room_id)
    # Spawn the room's Redis Pub/Sub listener task if not already running.
    # This must happen after manager.connect() so room_size() > 0.
    room_listener_registry.ensure_listening(room_id)

    redis: Redis = websocket.app.state.redis
    channel = f"{settings.pubsub_channel_prefix}{room_id}"

    try:
        while True:
            raw = await websocket.receive_text()
            # Validate that the frame is a JSON object before publishing.
            # Publishing raw avoids a redundant decode→encode round-trip.
            try:
                parsed = json.loads(raw)
                if not isinstance(parsed, dict):
                    raise ValueError("payload must be a JSON object")
            except (json.JSONDecodeError, ValueError) as exc:
                logger.warning("invalid frame dropped | room=%s | reason=%s", room_id, exc)
                continue

            await redis.publish(channel, raw)

    except WebSocketDisconnect:
        manager.disconnect(websocket, room_id)
        room_listener_registry.cancel_if_empty(room_id)
        logger.info("clean disconnect | room=%s | remaining=%d", room_id, manager.room_size(room_id))
    except Exception as exc:
        manager.disconnect(websocket, room_id)
        room_listener_registry.cancel_if_empty(room_id)
        logger.exception("unexpected ws error | room=%s | error=%s", room_id, exc)
